### ISSUE TITLE
logic error

### ISSUE THREAD

**Issue by hanmeimei888** [johnsonlee/booster.johnsonlee.io#3]
[https://github.com/johnsonlee/booster.johnsonlee.io/edit/master/docs/zh/guide/bugfixing/prevent-crash-from-system-bug.md](url)
`  private boolean isUserStackTrace(final StackTraceElement element) {
        final String name = element.getClassName();
        for (final String prefix : this.mIgnorePackages) {
            if (!name.startsWith(prefix)) {
                return true;
            }
        }
        return false;
    }`
the logic "true" and "false" here are reversed

**Comment by johnsonlee** [comment]
Thanks, already updated
